version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DJANGO_DEBUG=True

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: passwords
      POSTGRES_PASSWORD: password
      POSTGRES_DB: password
    ports:
      - "5432:5432"
